instance_types:
  - {name: m7i.xlarge,   family: general, ram_gb:  16, vcpu:  4, hourly_price_usd: 0.2016}
  - {name: m7i.2xlarge,  family: general, ram_gb:  32, vcpu:  8, hourly_price_usd: 0.4032}
  - {name: m7i.4xlarge,  family: general, ram_gb:  64, vcpu: 16, hourly_price_usd: 0.8064}
  - {name: m7i.8xlarge,  family: general, ram_gb: 128, vcpu: 32, hourly_price_usd: 1.6128}
  - {name: m7i.16xlarge, family: general, ram_gb: 256, vcpu: 64, hourly_price_usd: 3.2256}
  - {name: r7i.xlarge,   family: memory,  ram_gb:  32, vcpu:  4, hourly_price_usd: 0.2520}
  - {name: r7i.2xlarge,  family: memory,  ram_gb:  64, vcpu:  8, hourly_price_usd: 0.5040}
  - {name: r7i.4xlarge,  family: memory,  ram_gb: 128, vcpu: 16, hourly_price_usd: 1.0080}
  - {name: r7i.8xlarge,  family: memory,  ram_gb: 256, vcpu: 32, hourly_price_usd: 2.0160}
  - {name: r7i.16xlarge, family: memory,  ram_gb: 512, vcpu: 64, hourly_price_usd: 4.0320}
  - {name: c7i.xlarge,   family: compute, ram_gb:   8, vcpu:  4, hourly_price_usd: 0.1785}
  - {name: c7i.2xlarge,  family: compute, ram_gb:  16, vcpu:  8, hourly_price_usd: 0.3570}
  - {name: c7i.4xlarge,  family: compute, ram_gb:  32, vcpu: 16, hourly_price_usd: 0.7140}
  - {name: c7i.8xlarge,  family: compute, ram_gb:  64, vcpu: 32, hourly_price_usd: 1.4280}
  - {name: c7i.16xlarge, family: compute, ram_gb: 128, vcpu: 64, hourly_price_usd: 2.8560}
